### ISSUE TITLE
ulti_head_attention_forward     gaussian[0].permute(2, 0, 1) RuntimeError: number of dims don't match in permute

### ISSUE THREAD

**Issue by lucasjinreal** [gaopengcuhk/SMCA-DETR#10]
ulti_head_attention_forward
    gaussian[0].permute(2, 0, 1)
RuntimeError: number of dims don't match in permute

Does h_w shape is 1,Bs, 2?

for example: torch.Size([1, 10, 2])?

I got this error when run your code.

**Comment by hanqiu-hq** [comment]
Yes, the h_w has a shape of [1, bs, 2].
Did you delete the Brackets of tensor gaussian?
`https://github.com/gaopengcuhk/SMCA-DETR/blob/e4df3ab2081571a016c82794a85abd2342a2fc1b/models/transformer.py#L306`

**Comment by hanqiu-hq** [comment]
Yes, the h_w has a shape of [1, bs, 2].
Did you delete the Brackets of tensor gaussian?
`https://github.com/gaopengcuhk/SMCA-DETR/blob/e4df3ab2081571a016c82794a85abd2342a2fc1b/models/transformer.py#L306`

**Comment by hanqiu-hq** [comment]
Yes, the h_w has a shape of [1, bs, 2].
Did you delete the Brackets of tensor gaussian?
https://github.com/gaopengcuhk/SMCA-DETR/blob/e4df3ab2081571a016c82794a85abd2342a2fc1b/models/transformer.py#L306

**Comment by hanqiu-hq** [comment]
Yes, the tensor h_w has a shape of [1, bs, 2].
Did you delete the brackets of the tensor gaussian?
https://github.com/gaopengcuhk/SMCA-DETR/blob/e4df3ab2081571a016c82794a85abd2342a2fc1b/models/transformer.py#L306

**Comment by lucasjinreal** [comment]
@hanqiu-hq Hi, the error not comes from transformer decoder, but from SMCA attention forward:

```
 if naive:
        attn_output_weights = torch.bmm(q, k.transpose(1, 2))
        assert list(attn_output_weights.size()) == [
            bsz * num_heads, tgt_len, src_len]

        if attn_mask is not None:
            if attn_mask.dtype == torch.bool:
                attn_output_weights.masked_fill_(attn_mask, float('-inf'))
            else:
                attn_output_weights += attn_mask

        if key_padding_mask is not None:
            attn_output_weights = attn_output_weights.view(
                bsz, num_heads, tgt_len, src_len)
            attn_output_weights = attn_output_weights.masked_fill(
                key_padding_mask.unsqueeze(1).unsqueeze(2), float('-inf'),)
            attn_output_weights = attn_output_weights.view(
                bsz * num_heads, tgt_len, src_len)

        attn_output_weights = attn_output_weights + \
            gaussian[0].permute(2, 0, 1)
```
https://github.com/gaopengcuhk/SMCA-DETR/blob/e4df3ab2081571a016c82794a85abd2342a2fc1b/models/attention_layer.py#L264

which means gaussian[0] 's shape is not right, but tthis value how could it be wrong? images shape not problem, h_w no problem..

**Comment by hanqiu-hq** [comment]
The gaussian tensor has three dimensions with the shape of [tgt_len, H*W,  bs * num_head].
It is wrapped in a list when passing to the attention module.
https://github.com/gaopengcuhk/SMCA-DETR/blob/e4df3ab2081571a016c82794a85abd2342a2fc1b/models/transformer.py#L306
So the gaussian[0] in the attention module should have the same shape and num of dimensions as above.
you can try to print the shape of "gaussian[0]" in the attention module.

https://github.com/gaopengcuhk/SMCA-DETR/blob/e4df3ab2081571a016c82794a85abd2342a2fc1b/models/attention_layer.py#L264

**Comment by lucasjinreal** [comment]
@hanqiu-hq My guassian shape is:

```
gaussian shape:  torch.Size([100, 962, 80, 2])

```

seems wrong, seems the last shape [80, 2] is not right? the 2 is reduandent, what caused this error?

**Comment by lucasjinreal** [comment]
@hanqiu-hq And I think , maybe h_w shape is not as you told.... every variable shape I logged:

```
point shape:  torch.Size([100, 80, 2])
distance shape:  torch.Size([100, 858, 80, 2])
gaussian shape 0:  torch.Size([100, 858, 80, 2])
gaussian shape:  torch.Size([100, 858, 80, 2])
point shape:  torch.Size([100, 80, 2])
distance shape:  torch.Size([100, 864, 80, 2])
gaussian shape 0:  torch.Size([100, 864, 80, 2])
gaussian shape:  torch.Size([100, 864, 80, 2])

```

start from point shape, it was wrong..
from the code:

```
if self.layer_index == 0:
            point_sigmoid_ref_inter = self.point1(out)
            point_sigmoid_ref = point_sigmoid_ref_inter.sigmoid()
            point_sigmoid_ref = (h_w - 0) * point_sigmoid_ref / 32
            point_sigmoid_ref = point_sigmoid_ref.repeat(1, 1, 8)
        else:
            point_sigmoid_ref = point_ref_previous
        print('point_sigmoid_ref: ', point_sigmoid_ref.shape)
        point = point_sigmoid_ref + point_sigmoid_offset
        point = point.view(tgt_len, -1, 2)
        distance = (point.unsqueeze(1) - grid.unsqueeze(0)).pow(2)
        print('point shape: ', point.unsqueeze(1).shape)
        print('grid shape: ', grid.unsqueeze(0).shape)
        print('distance shape: ', distance.shape)
```

I can make sure, your code has problem. even grid shape is right 

```
grid 0 shape:  torch.Size([1092, 80, 2])

```

so which shape seems wrong here?

**Comment by hanqiu-hq** [comment]
The last dimension of tensor distance with shape [2] is eliminated at:
https://github.com/gaopengcuhk/SMCA-DETR/blob/e4df3ab2081571a016c82794a85abd2342a2fc1b/models/transformer.py#L292
So the tensor gaussian will have three dimensions with shape [tgt_len, H*W, bs * num_head] instead of [tgt_len, H*W, bs * num_head , 2].
Did you skip the code from L280-L298?
https://github.com/gaopengcuhk/SMCA-DETR/blob/e4df3ab2081571a016c82794a85abd2342a2fc1b/models/transformer.py#L280-L298

**Comment by lucasjinreal** [comment]
@hanqiu-hq  Holy shit... seems you set a value of a string to a default bool value....

![image](https://user-images.githubusercontent.com/21303438/140710630-7ca1e663-3737-442d-a3a3-4ee4c6b162ff.png)


What should I set here? type1 or type4?

**Comment by lucasjinreal** [comment]
@hanqiu-hq I started trained, the speed seems not very normal:

![image](https://user-images.githubusercontent.com/21303438/140715318-40d76023-03ef-451d-b70c-bd27e272d9ee.png)
