### ISSUE TITLE
Question about the FLOPs in Table 1

### ISSUE THREAD

**Issue by tangjiuqi097** [gaopengcuhk/SMCA-DETR#12]
Hi, why the FLOPs is much smaller than the DETR? As the SMCA uses multiple-level features, it should have larger FLOPs intuitively.

And what operations make the lower FLOPs have a slower inference speed? 
For example, SMCA-DC5 153GFLOPs 0.100s vs. DETR 187GFLOPs 0.079.

![image](https://user-images.githubusercontent.com/22868536/141767038-254a24d2-1adf-4643-94ed-c6ee25cfc0b8.png)

**Comment by gaopengcuhk** [comment]
DETR-DC5 adds dilation in ResNet while Multi-scale SMCA does not have dilation in ResNet. Besides, our SMCA only uses downsample 16, 32, and 64 feature maps while Deformable DETR and other feature pyramid methods utilize downsample 8, 16, 32, and 64 feature maps. These two reasons result in SMCA-DETR with small FLOPs.

Thanks very much for your good question. We will add this explanation in our paper.

**Comment by tangjiuqi097** [comment]
Thanks for your reply. But SMCA uses the downsample 16 feature map which has the same size as the DC5 feature, why the FLOPs is much smaller than the DETR-DC5?

**Comment by tangjiuqi097** [comment]
I got it. The backbone will cost less FLOPs.
