### ISSUE TITLE
pretrained model download link

### ISSUE THREAD

**Issue by lucasjinreal** [gaopengcuhk/SMCA-DETR#13]

**Comment by gaopengcuhk** [comment]
We release Container+Single-scale SMCA which can achieve 44.2-44.4 mAP compared with ResNet50+Scale-scale SMCA which achieve 41.0mAP.

**Comment by gaopengcuhk** [comment]
https://drive.google.com/file/d/1dFkr1QAbBpX2Gss0nl4TQ--URUTK7TZ0/view?usp=sharing

**Comment by lucasjinreal** [comment]
@gaopengcuhk thank u. How's the speed compare with r50?

**Comment by gaopengcuhk** [comment]
On Imagenet classification(224), Container is comparable with R50 on FLOPs and speed with much better performance. On Object detection which requires 1333 large resolution, Container is slower than R50. I do not benchmark the speed.

**Comment by lucasjinreal** [comment]
@gaopengcuhk why container is slower in large input ?

**Comment by gaopengcuhk** [comment]
All Transformer based models like PVT, Container, SWIN is slower than ResNet 50 on large image.
