### ISSUE TITLE
OOM for ResNet50-DC5 even for 32GB GPUs

### ISSUE THREAD

**Issue by yformer** [gaopengcuhk/SMCA-DETR#15]
Hi, 

I tried to run ResNet50-DC5 for SMCA-DETR on 8 GPUs with 32 GB memory each. It shows OOM error when using ResNet50-DC5 with batch size 16. Why it uses so much memory than other models?

**Comment by gaopengcuhk** [comment]
SMCA-DETR do not support Dilation. Please use a multi-scale bi-directional depthwise encoder in multi-scale smca.zip.

**Comment by gaopengcuhk** [comment]
Besides, the original DETR with Dilation also set the images per GPU to 1.

**Comment by yformer** [comment]
> Besides, the original DETR with Dilation also set the images per GPU to 1.

If it requires the image per GPU to be 1, then what is the improvement of training efficiency gain? For standard DETR, it can  set 4 images for each GPU with 32 GB GPU memory, which can lead to almost 4x speed up than SMCA. For other efficient heads, this will be super inefficient.

**Comment by yformer** [comment]
> 

For ResNet50-DC5, it is just a feature input from backbone. This is a common case. If this is not supported, I do not know what kind of backbone will work for SMCA-DETR. Can you elaborate it?

**Comment by gaopengcuhk** [comment]
Can you train DETR-DC5 with batch 2 per GPU?

**Comment by gaopengcuhk** [comment]
DETR uses DC5 to include a high-resolution feature map. SMCA uses a bidirectional multi-scale depthwise convolution encoder to include a high-resolution feature map.

**Comment by gaopengcuhk** [comment]
Can you send me an email? It is easier to discuss on wechat.

**Comment by yformer** [comment]
> Can you train DETR-DC5 with batch 2 per GPU?

Yes

**Comment by yformer** [comment]
> DETR uses DC5 to include a high-resolution feature map. SMCA uses a bidirectional multi-scale depthwise convolution encoder to include a high-resolution feature map.

Multi-level features as DeformableDETR?

**Comment by yformer** [comment]
> Can you send me an email? It is easier to discuss on wechat.

Is this your email address, 1155102382 at link.cuhk.edu.hk?

**Comment by gaopengcuhk** [comment]
gaopeng [at] pjlab (dot) org (dot) cn
