### ISSUE TITLE
How to use target GPU for training？

### ISSUE THREAD

**Issue by Huzhen757** [gaopengcuhk/SMCA-DETR#20]
![3EFVR_ZLQHA`CZ)C LV{481](https://user-images.githubusercontent.com/65730183/146333800-f03e3e83-56a3-45c4-abaf-42de805cf1d7.jpg)
![J 6{N G(Z(K0@~X4BCDRLA5](https://user-images.githubusercontent.com/65730183/146333860-f47ed364-e472-45b1-88eb-b08694fa2747.png)

你好，作者，我想使用指定GPU来完成多卡训练，为什么这里会报错呢？请问该如何指定GPU型号来完成多GPU训练，是需要在代码中修改吗？
希望可以收到您的答复

**Comment by shilinyan99** [comment]
Hello, I am also watching SMCA. Can you add me as a friend and then we can discuss and communicate together? My email is tattoo_lin@foxmail.com

**Comment by gaopengcuhk** [comment]
put CUDA_VISIBLE_DEVICES=0,1,2,3 before python
