### ISSUE TITLE
Searching for help about the visiulization image.

### ISSUE THREAD

**Issue by Tchuanm** [gaopengcuhk/SMCA-DETR#22]
It's A nice job. 
Could you guide/tell me how to plot the visualization co-attention image of FIgure 2/3 in your paper. I want to visualise some my own images in your repo. 
Thanks very much.

**Comment by gaopengcuhk** [comment]
Thank you for your interest in our research. We will respond to you in the near future.

**Comment by Tchuanm** [comment]
Thanks, looking forward.

**Comment by minghangz** [comment]
Thank you for your interest in our work. You can visualize your image according to the following steps:

- Determine which query predicts the object you want to visualize by the predicted object class probability ([here](https://github.com/gaopengcuhk/SMCA-DETR/blob/e4df3ab2081571a016c82794a85abd2342a2fc1b/models/detr.py#L79)).
- Get the Gaussian mask for the queries from [here](https://github.com/gaopengcuhk/SMCA-DETR/blob/e4df3ab2081571a016c82794a85abd2342a2fc1b/models/transformer.py#L300), and the shape should be (num_queries, H\*W, batch_size\*num_attention_heads). The Gaussian mask here is not exponentiated.
- Average the Gaussian masks of each attention heads, perform exponential operation, and reshape them to (num_queries, H, W, batch_size).
- Finally you can overlay the corresponding Gaussian mask with the image and visualize it (e.g. using Matplotlib).

**Comment by Tchuanm** [comment]
Thanks for that. I will try&visualize it.
