### ISSUE TITLE
Some question about the SMCA module and the code 

### ISSUE THREAD

**Issue by Huzhen757** [gaopengcuhk/SMCA-DETR#3]
Hi，I'm very interested in your work about the newly decoder of DETR。I have some questions about your code：
1. When I debugged your source code, I didn't find the use of encoder in FPN, such as Intra-Scale self-attention and multi-scale self- attention mentioned in the paper; And the Scale Selection network in the decoder。
2.  Does the 'type1'-'type4' parameters in the code only change how to generate the Gaussian-like weights map? 
3.  In the decoder layer in Transformer，the propagate process：
     out = self.norm4(tgt + query_pos) 
     point_sigmoid_offset = self.point2(out)
Is the point_sigmoid_offset parameter corresponds to sw and sh in the paper？

    if self.layer_index == 0:
            point_sigmoid_ref_inter = self.point1(out) 
            point_sigmoid_ref = point_sigmoid_ref_inter.sigmoid() 
            point_sigmoid_ref = (h_w - 0) * point_sigmoid_ref / 32 
            point_sigmoid_ref = point_sigmoid_ref.repeat(1, 1, 8)  # [100, bs, 2] -> [100, bs, 16]
        else: 
            point_sigmoid_ref = point_ref_previous
        point = point_sigmoid_ref + point_sigmoid_offset

Is the point_sigmoid_ref parameter corresponds to cw and ch in the paper? Why do these two parameters need to be added?
     distance = (point.unsqueeze(1) - grid.unsqueeze(0)).pow(2)
This step corresponds to (i-cw) ^ 2 + (j-ch) ^ 2 in G (I, J) in the paper;

      if self.dynamic_scale == "type1":
            scale = 1
            distance = distance.sum(-1) * scale 
        elif self.dynamic_scale == "type2": # 对于type2:对out2再做一次线性映射 
            scale = self.point3(out)  # [100, bs, 256] -> [100, bs, 8]
            scale = scale * scale     # 
            scale = scale.reshape(tgt_len, -1).unsqueeze(1)
            distance = distance.sum(-1) * scale
        elif self.dynamic_scale == "type3":
            scale = self.point3(out)
            scale = scale * scale
            scale = scale.reshape(tgt_len, -1, 2).unsqueeze(1)
            distance = (distance * scale).sum(-1)
        elif self.dynamic_scale == "type4":
            scale = self.point3(out)
            scale = scale * scale
            scale = scale.reshape(tgt_len, -1, 3).unsqueeze(1)
            distance = torch.cat([distance, torch.prod(distance, dim=-1, keepdim=True)], dim=-1)
            distance = (distance * scale).sum(-1)
        # generate Gaussian-like weight map
        gaussian = -(distance - 0).abs() / self.smooth
According to the operation in the code, it seems that G (I, J) in the paper can not be obtained, I don't know what these steps meaning? 
4. In addition, the paper says that `logGi'` needs to be added to generate the Co-attention weights map in the Co-attention of the decoder in the transformer, but the code is set as follows:
           `attn_output_weights = attn_output_weights + gaussian[0].permute(2, 0, 1)`      

I sincerely hope you can help me solve these problems . Thanks !

**Comment by gaopengcuhk** [comment]
Thank you for your interest in SMCA.

1. The official released SMCA is the single-scale version which does not need intra-scale and multi-scale attention and scale-selection network. I will send you an unpolished version of multi-scale SMCA.
2. type1'-'type4' only change Gaussian-like attention map.
3. point_sigmoid_ref = point_sigmoid_ref_inter.sigmoid(). This corresponds to cs and cw. As cs and cw are centers in normalized coordinate. We direct get log G instead of G. By simple mathematical induction, you can find that log G is the same as implemented in our codebase.
4. attn_output_weights is the co-attention before softmax. The implementation you refer to is the same as equation 5 in the paper. After the addition of log G with co-attention, we add a softmax normalization.

**Comment by Huzhen757** [comment]
Thanks for your  carefully reply。
1.  In other words，point_sigmoid_ref is corresponds to  head-shared center [cw, ch] in the paper。Therefore, it's  only need to this parameter in the first generation in the first decoder layer, the parameter will not change in the later decoder。Besides, the parameter point_sigmoid_offset is corresponds to head-specific center offset, This parameter is generated in each decoder。Also，the parameter 'type1'-'type4' is corresponding to the generation of scale，as well as the scale is corresponds to head-specific scales sw,i and sh,i。

2. When calculating the loss, why use  head-shared center add FFN(f) for calculating the predicted value of bbox? like this:
     outputs_coord[..., :2] = outputs_coord[..., :2] + points
Why not choose head-specific center offset to add FFN(f) as the predict value of bbox?What is the purpose of this choice?

3. Finally，when I training the model with the DC5 backbone and using the type3 for generate scales。Even though I used one  3090 with 24G memory to training，but the batch size only be set to 1。So，If training the whole 300 epochs，it will take too much time。So I want to ask, could you provide preweights about the SMCA model。

**Comment by gaopengcuhk** [comment]
Please check the newly added Multi_scale_SMCA.zip. I will share a Container-M SMCA which achieves 47 mAP.

**Comment by Huzhen757** [comment]
Fine. Thank you very much!  Excuse me, did you send it to my email ？

**Comment by gaopengcuhk** [comment]
I have added a multi-scale-smca.zip file in Github .

**Comment by Huzhen757** [comment]
Thank  you.  Can you provide me the download address of the  preweight of the Contianer-M SMCA model?

**Comment by gaopengcuhk** [comment]
I will send you the pretrained Container-M SMCA within 2days. By the way, the DETR-series model with Dilated Backbone needs large GPU memory. Even with a large GPU memory, the batch size needs set to be 1.

**Comment by Huzhen757** [comment]
OK，I know , Thank you very much! When I debug DMS-MH-GMCA model, In the forward of backbone:
`    def forward(self, tensor_list: NestedTensor):
        pdb.set_trace()
        xs = self.body(tensor_list.tensors)
        out: Dict[str, NestedTensor] = {}
        for name, x in xs.items():
            m = tensor_list.mask
            assert m is not None
            mask = F.interpolate(m[None].float(), size=x.shape[-2:]).to(torch.bool)[0]
            out[name] = NestedTensor(x, mask)
        return out`
its report an warning,like this: 
PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.

Besides, when I train the DMS-MH-GMCA model, it can't train normally：
 Start training
> /media/data2/huzhen/Fast-DETR/DMS-MH-GMCA-main_very_important/models/backbone.py(74)forward()
-> xs = self.body(tensor_list.tensors)
(Pdb)

**Comment by Huzhen757** [comment]
Another, When I comment out this line. The problem disappeared. But in the forward function in the EncoderLayer,。when feature fusion is performed, the shape of the feature map does not match,like this:
`           src_8 = src[0] + self.dropout1(self.conv_2(src2_8 + src2_16_8))
           src_16 = src[1] + self.dropout1(self.conv_2(src2_16 + src2_32_16 + src2_8_16))
           src_32 = src[2] + self.dropout1(self.conv_2(src2_32 + src2_64_32 + src2_16_32))
           src_64 = src[3] + self.dropout1(self.conv_2(src2_64 + src2_32_64))`

the src_32 report a error: 
` The size of tensor a (54) must match the size of tensor b (27) at non-singleton dimension 3.`

Because  the feature map src_32 and src_64_32 has a same shape 【bs,. 256, h/16, w/16】, but the feature map  src2_16_32 is  downsampling by q_16, besides q_16 shape is 【bs,. 256, h/16, w/16】，so the shape is 【bs,. 256, h/32, w/32】after downsample. How can I make solved?

**Comment by gaopengcuhk** [comment]
There are two transformer models, namely transformer.py and transformer_44_dot_4.py. Which one are you using? Please use transformer_44_dot_4.py instead of transformer.py. Transformer_44_dot_4.py means the mAP is 44.4.

**Comment by Huzhen757** [comment]
好的，我之前是使用transformer.py这个脚本的，因为你的这个mian脚本是自己调用transformer.py脚本去搭建Transformer的，那么在调用的时候改一下，改成transformer_44_dot_4这个脚本来搭建Transformer再试试

**Comment by Huzhen757** [comment]
我换了transformer_44_dot_4这个脚本来搭建Transformer依旧存在问题， 和transformer脚本一样: 
`RuntimeError: The size of tensor a (59) must match the size of tensor b (30) at non-singleton dimension 3`
因为在进行feature fusion的时候：
`src_32 = src[2] + self.dropout1(self.conv_2(src2_32 + src2_64_32 + src2_16_32))`
这里的src2_32和src2_64_32的shape是相同的，可以进行Add操作，但是对于特征图src2_16_32,他是由src2_16进行下采样得来的。
而src2_16的shape与src2_32，src2_64_32是相同的，都是相对于原图像下采样了16倍，因此再对src2_16进行下采样，得到的h和w
与其他两个是不一样的，就无法进行feature fusion。
请问代码这里是不是写错了？

**Comment by gaopengcuhk** [comment]
I run the code with the following training script.

python -m torch.distributed.launch --master_port=4234  --nproc_per_node=8 --use_env main.py --coco_path ../../../data/coco --batch_size 1 --lr_drop 100 --num_queries 300 --epochs 150 --dynamic_scale type3  --enc_layers 6 --dim_feedforward 1024

There seems to be no error happened.

**Comment by gaopengcuhk** [comment]
To replicate the results, you can set lr_drop to 40 and epochs to 50.

**Comment by gaopengcuhk** [comment]
In multi-scale SMCA, we only support batch 1 for training and inference.

**Comment by Huzhen757** [comment]
这些都是训练细节，我知道，这个并不影响代码的运行，只是在精度上会有所影响。现在的问题是无论使用transformer_44_dot_4脚本还是使用transformer这个脚本中去搭建Transformer时，其中的TransformerEncoderLayer的forward函数中，进行feature fusion时，会报错：
`    src_32 = src[2] + self.dropout1(self.conv_2(src2_32 + src2_64_32 + src2_16_32))
RuntimeError: The size of tensor a (54) must match the size of tensor b (27) at non-singleton dimension 3
`
因为这里的feature map的shape不匹配，所以无法直接进行Add操作，请问这里该如何去修改呢？

**Comment by gaopengcuhk** [comment]
I run the multi-scale code on my server. Using the following script.

python -m torch.distributed.launch --master_port=4234 --nproc_per_node=8 --use_env main.py --coco_path ../../../data/coco --batch_size 1 --lr_drop 100 --num_queries 300 --epochs 150 --dynamic_scale type3 --enc_layers 6 --dim_feedforward 1024

The code runs smoothly without error.

**Comment by gaopengcuhk** [comment]
Can you share your training script?

**Comment by gaopengcuhk** [comment]
I ran the code again. There is no error in my server.

**Comment by gaopengcuhk** [comment]
<img width="563" alt="Screen Shot 2021-09-11 at 10 58 10 AM" src="https://user-images.githubusercontent.com/51525797/132933978-d9f0e3c2-b717-4fc6-adf6-adf9a8bb09a6.png">

**Comment by Huzhen757** [comment]
我使用的是一张24G的3090去跑的，然后超参数基本上没有大的改动，唯一的改动在dim_feedrorward这里，我设置的是2048. 其他都是按照你的默认值的，并且使用的是DMS-MH-GMCA-main_very_important这个文件夹下面的main脚本去跑的。

**Comment by gaopengcuhk** [comment]
My PyTorch version is listed below:

pytorch                  1.8.1           py3.7_cuda11.1_cudnn8.0.5_0    pytorch

**Comment by Huzhen757** [comment]
是不是我使用的DC model的原因呢？我在dilation参数中设置了True

**Comment by gaopengcuhk** [comment]
The multi-scale model is in-compatible with dilation. In SMCA, we use backbone without dilation for single and multi-scale.

**Comment by Huzhen757** [comment]
我的torch_version是1.7.1 cuda11.1

**Comment by gaopengcuhk** [comment]
Please turn off dilation in the backbone.

**Comment by Huzhen757** [comment]
Ok，我将dilation参数设置成False，这个地方不再报错了，SMCA应该是不支持dilation conv的，只能是普通的resnet50或者resnet101作为backbone。
非常感谢您的回复，请问关于SMCA model的预训练权重什么时候提供呢？

**Comment by gaopengcuhk** [comment]
Container-SMCA with pretrained model will be officially released under Container codebase. 
https://github.com/gaopengcuhk/Container

**Comment by Huzhen757** [comment]
Ok,&nbsp;Thank you very much.&nbsp;
Will it include the preweight of model SMCA(new multi-scale) with res50 backbone。
另外，我想问下，无论是使用res50作为backbone还是container作为backbone，single-scale SMCA的encoder输入都是只有一个level的feature map对吧？也就是原始版本中的代码？
然后，还有一个问题，我在debug&nbsp;DMS-MH-GMCA模型时，在decoder中发现：
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;distance_8&nbsp;=&nbsp;(distance_8&nbsp;*&nbsp;scale1).sum(-1)&nbsp;*&nbsp;0.5&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;distance_16&nbsp;=&nbsp;(distance_16&nbsp;*&nbsp;scale2).sum(-1)&nbsp;*&nbsp;0.5
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;distance_32&nbsp;=&nbsp;(distance_32&nbsp;*&nbsp;scale3).sum(-1)&nbsp;*&nbsp;1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;distance_64&nbsp;=&nbsp;(distance_64&nbsp;*&nbsp;scale4).sum(-1)&nbsp;*&nbsp;2

4个level的feature map在求对应的distance时，乘上了不同的权重因子，请问这个设计的出发点是什么？可以解释一下吗？


最后，比如我有两张24G的3090，设备号为2，3，可以指定GPU型号去训练模型吗？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gaopengcuhk/SMCA-DETR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 中午1:51
***@***.***&gt;;
抄送:&nbsp;"Hide on ***@***.******@***.***&gt;;
主题:&nbsp;Re: [gaopengcuhk/SMCA-DETR] Some question about the SMCA module and the code  (#3)





 
Container-SMCA with pretrained model will be officially released under Container codebase.
 https://github.com/gaopengcuhk/Container
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gaopengcuhk** [comment]
1 . We will release Container-Light + SMCA and Container-M + SMCA, in the future, we will incorporate Container + Multi-Scale SMCA. Single-scale always use the last layer of backbone.
2. 0.5, 0.5, 1, 2 are \beta in equation 4. \beta control scale of gaussian. As different feature map has different spatial resolution, we choose a different \beta for different scale to approximately cover the same spatial region. 
3. You can use CUDA_VISIBLE_DEVICES=2,3.

**Comment by Huzhen757** [comment]
Ok ， Thank you very much！
我在debug的时候发现TramsformerDecoderLayer这个类中：
&nbsp;if&nbsp;self.head_mixture:
&nbsp;&nbsp;&nbsp;&nbsp;gaussian&nbsp;=&nbsp;gaussian&nbsp;*&nbsp;torch.tensor([1,1,1,1,0,0,0,0]).repeat(bs).unsqueeze(0).unsqueeze(0).to(tgt.device).float()
&nbsp;if&nbsp;self.query_mixture:
&nbsp;&nbsp;&nbsp;gaussian&nbsp;=&nbsp;torch.cat([torch.zeros(tgt_len&nbsp;//&nbsp;2),&nbsp;torch.ones(tgt_len&nbsp;//&nbsp;2)]).unsqueeze(-1).unsqueeze(-1).to(gaussian.device)&nbsp;*&nbsp;gaussian






请问这两个参数是控制Gaussian-like weights map的什么呢？
如果开启head_mixture为True，那么此时的Gaussian-like weights map就会只关注前4个head，而后4个head将不再关注？


而query_mixture这个bool值又是控制什么的呢？并且在DETR中对于bbox的预测值也会进行该判断：
if&nbsp;self.query_mixture:
&nbsp;&nbsp;&nbsp;outputs_coord[:,&nbsp;:,&nbsp;:,&nbsp;:2]&nbsp;=&nbsp;outputs_coord[:,&nbsp;:,&nbsp;:,&nbsp;:2]&nbsp;+&nbsp;points&nbsp;*&nbsp;torch.cat([torch.zeros(self.num_queries&nbsp;//&nbsp;2),&nbsp;
   torch.ones(self.num_queries&nbsp;//&nbsp;2)]).unsqueeze(-1).unsqueeze(0).unsqueeze(0).to(points)
else:
&nbsp;&nbsp; outputs_coord[:,&nbsp;:,&nbsp;:,&nbsp;:2]&nbsp;=&nbsp;outputs_coord[:,&nbsp;:,&nbsp;:,&nbsp;:2]&nbsp;+&nbsp;points












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gaopengcuhk/SMCA-DETR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 下午5:44
***@***.***&gt;;
抄送:&nbsp;"Hide on ***@***.******@***.***&gt;;
主题:&nbsp;Re: [gaopengcuhk/SMCA-DETR] Some question about the SMCA module and the code  (#3)





 
1 . We will release Container-Light + SMCA and Container-M + SMCA, in the future, we will incorporate Container + Multi-Scale SMCA. Single-scale always use the last layer of backbone.
 2. 0.5, 0.5, 1, 2 are \beta in equation 4. \beta control scale of gaussian. As different feature map has different spatial resolution, we choose a different \beta for different scale to approximately cover the same spatial region.
 3. You can use CUDA_VISIBLE_DEVICES=2,3.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Huzhen757** [comment]
你好，作者，我想使用指定GPU来完成多卡训练，为什么这里会报错呢？请问该如何指定GPU型号来完成多GPU训练，是需要在代码中修改吗？
希望可以收到您的答复


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gaopengcuhk/SMCA-DETR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 下午5:44
***@***.***&gt;;
抄送:&nbsp;"Hide on ***@***.******@***.***&gt;;
主题:&nbsp;Re: [gaopengcuhk/SMCA-DETR] Some question about the SMCA module and the code  (#3)





 
1 . We will release Container-Light + SMCA and Container-M + SMCA, in the future, we will incorporate Container + Multi-Scale SMCA. Single-scale always use the last layer of backbone.
 2. 0.5, 0.5, 1, 2 are \beta in equation 4. \beta control scale of gaussian. As different feature map has different spatial resolution, we choose a different \beta for different scale to approximately cover the same spatial region.
 3. You can use CUDA_VISIBLE_DEVICES=2,3.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lsabrinax** [comment]
thanks for your work! I have a question about the code of producing gaussian weight map`distance = (distance * scale).sum(-1)`, why it is multiplication rather than division.
