### ISSUE TITLE
关于多尺度SMCA的代码

### ISSUE THREAD

**Issue by sirius541** [gaopengcuhk/SMCA-DETR#5]
作者您好，我看了下您的多尺度代码，您的在多尺度code中transformer的编码层是完全用卷积实现的，没有用到attn，您这么做的意义是什么呢？

**Comment by gaopengcuhk** [comment]
Replacing multi-scale depthwise convolution with multi-scale attention mentioned in the original ICCV can improve the mAP from 43.7 => 44.4 with fewer FLOPs, faster training, and less GPU memory.

**Comment by gaopengcuhk** [comment]
We will update our ICCV submission with an explanation and results of the multi-scale bi-directional depthwise encoder.

**Comment by gaopengcuhk** [comment]
Encoder    Atten=>DW
R50           43.7=>44.4
R101          44.4=>45.7

**Comment by sirius541** [comment]
谢谢您的回复！ 您的意思是您论文的结果是使用attn做的，但是使用depthwise conv可以达到更高的精度，占用更少的计算资源是吗？

**Comment by gaopengcuhk** [comment]
thanks for your interest in our paper.
