### ISSUE TITLE
Question about use multi-GPU for training

### ISSUE THREAD

**Issue by Huzhen757** [gaopengcuhk/SMCA-DETR#6]
Hi， I want to try use 4 gpus to train your model DMS_MH_GMCA_resnet50 by myself, but it's report a warning,，like this：
![683984ba833dcb8dd9fa60d93ca70df](https://user-images.githubusercontent.com/65730183/136571586-e231779d-05cc-430b-87ee-347009d867da.png)

Will this warning affect the accuracy of training？
Thanks ！

**Comment by gaopengcuhk** [comment]
The warning will not affect the training accuracy.

**Comment by Huzhen757** [comment]
OK，thank you very much！
