### ISSUE TITLE
what's the modification compare with original DETR

### ISSUE THREAD

**Issue by lucasjinreal** [gaopengcuhk/SMCA-DETR#7]
Hi, just wonder, except for the GaussianAttention and the transformers.py, anything else changed compare with original DETR?

**Comment by gaopengcuhk** [comment]
SMCA uses 1)focal loss and 2) perform bounding box regression conditioned on the center of the predicted gaussian center.

**Comment by lucasjinreal** [comment]
@gaopengcuhk where are the codes in terms of these 2 modofications.

**Comment by gaopengcuhk** [comment]
For focal loss, we modified detr.py loss_labels function and matcher.py HungarianMatcher.

**Comment by gaopengcuhk** [comment]
For perform bounding box regression conditioned on the center of the predicted gaussian center, we modify detr.py line 84
