### ISSUE TITLE
About input format

### ISSUE THREAD

**Issue by lucasjinreal** [gaopengcuhk/SMCA-DETR#9]
at this line code:

```
if isinstance(samples[0], (list, torch.Tensor)):
            samples[0] = nested_tensor_from_tensor_list(samples[0])
```

Since samples already is NestedTensor, why still need nested_tensor_from_tensor?

Besides, have u tested d2 version of SMCA? It's not work... the input is quit different from original DETR

**Comment by hanqiu-hq** [comment]
Our SMCA is implemented based on the original [DETR](https://github.com/facebookresearch/detr/tree/main/d2). So we keep the same type-checking code for the input tensor as DETR,  although the image tensors(samples) are already wrapped into NestedTensor by collate_fn in the dataloader.

For the second question, we have not implemented SMCA based on detectron2, so there is only the origin DETR code in the d2 folder. This is our mistake and we will delete the d2 folder.

**Comment by lucasjinreal** [comment]
@hanqiu-hq Hi, I noticed that original DETR using:

```
if isinstance(samples, (list, torch.Tensor)):
            samples = nested_tensor_from_tensor_list(samples)
```

so samples[0] is images, samples[1] is targets?

Just wonder what's proper shape of h_w get from samples[1]? I posted an issue about it, it can not pass attention calculation

**Comment by yformer** [comment]
> @hanqiu-hq Hi, I noticed that original DETR using:
> 
> ```
> if isinstance(samples, (list, torch.Tensor)):
>             samples = nested_tensor_from_tensor_list(samples)
> ```
> 
> so samples[0] is images, samples[1] is targets?
> 
> Just wonder what's proper shape of h_w get from samples[1]? I posted an issue about it, it can not pass attention calculation

Same here. I do not understand what is samples[0] and what is samples[1]. @gaopengcuhk, can you explain it?

**Comment by yformer** [comment]
If samples[1] is a target, how do you do it when performing inference?

**Comment by lucasjinreal** [comment]
@yformer  samples[1] is image original sizes, I have modified it into d2 version ,works OK from now.

**Comment by yformer** [comment]
> @yformer samples[1] is image original sizes, I have modified it into d2 version ,works OK from now.

@jinfagang, can you share that part of code? I also tried to modify it into d2 version. But it does not work. 

`        if isinstance(samples, (list, torch.Tensor)):`
`            samples = nested_tensor_from_tensor_list(samples)`
`        features, pos = self.backbone(samples)`

`        h_w = torch.stack([torch.stack([inst['size'] for inst in samples])[:, 1],`
 `                          torch.stack([inst['size'] for inst in samples])[:, 0]], dim=-1)`
 `       h_w = h_w.unsqueeze(0)`

**Comment by lucasjinreal** [comment]
@yformer But the question is, seems AP up to 25 then converge become slow, very very slow.....

you just need make h_w size to 1, bs, 2 then it can run. Also, since SMCA doesn't did any modification in d2, you gonna need also resolve some params settings, as well as Criterion, they are different then detr.

**Comment by yformer** [comment]
> @yformer But the question is, seems AP up to 25 then converge become slow, very very slow.....
> 
> you just need make h_w size to 1, bs, 2 then it can run. Also, since SMCA doesn't did any modification in d2, you gonna need also resolve some params settings, as well as Criterion, they are different then detr.

Is that because h_w is not set correctly, which makes the convergence slow? 

The shape of h_w is 1Xb_sX2. But what is the value for h_w, [[h, w], [h, w], [h, w]] or its normalized version? For d2 modification, I have completed it. The only concern is for the h_w part. Can you share that part code? So that we can double check if the performance can be reproducible.

**Comment by lucasjinreal** [comment]
@yformer I found the AP can not goes up because of the lr scheduler, now seems can converge

**Comment by yformer** [comment]
@jinfagang Can you reproduce the reported results from the paper with your d2go modification? And what is your batch size and learning rate for the training?

**Comment by yformer** [comment]
@jinfagang, when I ran my d2go code, it shows "IndexError: list index out of range" when performing inference. Did you see this error? Is it possible to share the value of  h_w?

**Comment by gaopengcuhk** [comment]
For multi-scale SMCA, only batch 1 per GPU  is supported.

**Comment by yformer** [comment]
> For multi-scale SMCA, only batch 1 per GPU is supported.

@gaopengcuhk, can you explain a little bit about samples[1], which is only used for obtaining h_w? If samples[1] is used to obtain original image size, why not using samples[0] directly?

**Comment by gaopengcuhk** [comment]
@yformer Thanks for your interest in our paper. We will respond to you within 3 days.

**Comment by lucasjinreal** [comment]
@yformer My implementation on d2 of SMCA seems not fully right,  I can not reproduce bs=16 AP on 8 GPUs.

I got only mAP 37 on 260000 iterations.

**Comment by yformer** [comment]
> @yformer Thanks for your interest in our paper. We will respond to you within 3 days.

@gaopengcuhk Any update?

**Comment by yformer** [comment]
> @yformer My implementation on d2 of SMCA seems not fully right, I can not reproduce bs=16 AP on 8 GPUs.
> 
> I got only mAP 37 on 260000 iterations.

Yeah, it looks not correct.

**Comment by yformer** [comment]
39.09 AP or 40.38 AP can be obtained. But it still has a gap between the reported one and the one I got.

**Comment by lucasjinreal** [comment]
@yformer How long have u trained? with how many bs? I found a bug in my code, it seems correct now, but converge speed is not as faster as AnchoDETR does, it got only 28 AP in 13 hours

**Comment by rshaojimmy** [comment]
So what is h_w exactly?

**Comment by FocusGZL** [comment]
> > [@yformer](https://github.com/yformer) samples[1] is image original sizes, I have modified it into d2 version ,works OK from now.
> 
> @jinfagang, can you share that part of code? I also tried to modify it into d2 version. But it does not work.
> 
> ` if isinstance(samples, (list, torch.Tensor)):` ` samples = nested_tensor_from_tensor_list(samples)` ` features, pos = self.backbone(samples)`
> 
> ` h_w = torch.stack([torch.stack([inst['size'] for inst in samples])[:, 1],` ` torch.stack([inst['size'] for inst in samples])[:, 0]], dim=-1)` ` h_w = h_w.unsqueeze(0)`

请问这个问题当初您解决了吗？如何解决的？
